version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      npm:
        patterns:
          - "*"
    ignore:
      # ignore to keep in sync with node24 used by GH runners
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      # ignore until ESLint supports TS 7
      - dependency-name: "typescript"
        versions: [">=7"]
