name: "CI: Unit-test, lint"

"on":
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test-lint:
    name: Run tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Ensure workflow actions use immutable refs
        uses: joshjohanning/ensure-immutable-actions@bc90ba67ffdea94121d930e649ba3d6219dcf275 # v2.7.0
        with:
          include-first-party: "true"
          write-job-summary: "on-failure-only"
          exclude-workflows: ".github/workflows/test_live-untag.yml"

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linters
        run: npm run lint

      - name: Check links in markdown
        uses: tcort/github-action-markdown-link-check@e047c5b37f24ab722bbef1a27b6fab7f96bc4068 # v1.1.3
        with:
          use-verbose-mode: true
